name: Generate binary and distribute it

on:
  release:
    types: [released]

jobs:
  generate-binary-and-distribute:
    name: Generate binary and distribute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install project dependencies
        run: yarn install --immutable
      - name: Bundle library
        run: yarn build
      - name: Run create binary
        run: yarn dist-standalone
      - name: Test binary
        run: ./datadog-ci-linux version
      - name: Upload asset to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./datadog-ci-*
