name: Generate binary and distribute it

on:
  workflow_dispatch:
  push:
    branches:
      - juan-fernandez/hackathon-bundle

jobs:
  generate-binary-and-distribute:
    name: Generate binary and distribute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install project dependencies
        run: yarn install --immutable
      - name: Bundle library
        run: yarn build
      - name: Run create binary
        run: yarn dist-standalone
      # - name: Test binary
      #   run: ./datadog-ci-linux help
      - name: Upload to draft release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ./datadog-ci-linux
            ./datadog-ci-macos
            ./datadog-ci-win.exe
          fail_on_unmatched_files: true
