name: Publish package on NPM
on:
  release:
    types: [prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: echo $GITHUB_REF
        env:
          NPM_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}
          TAG: ${{github.event.release.tag_name}}
